GET http://localhost:8080/api/v1/orders
Accept: application/json

###

GET http://localhost:8080/api/v2/orders
Accept: application/json

###

GET http://localhost:8080/api/v3/orders
Accept: application/json

###

GET http://localhost:8080/api/v3.1/orders?offset=0&limit=100
Accept: application/json

###

GET http://localhost:8080/api/v4/orders
Accept: application/json

###

GET http://localhost:8080/api/v6/orders
Accept: application/json

###